const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        LoginRequest: {
            email: "john.doe@example.com",
            password: "abc123"
        },
        RegisterRequest: {
            firstName: "John",
            lastName: "Doe",
            userName: "johndoe",
            email: "john.doe@example.com",
            password: "abc123",
            address: "123 Main St",
            telephoneNumber: "123-456-7890"
        },
        AddBrandRequest: {
            name: "samsung"
        },
        UpdateBrandRequest: {
            name: "Updated Brand Name"
        },
        AddToCartRequest: {
            userId: 1,
            productId: 1,
            quantity: 1
        },
        UpdateCartItemRequest: {
            quantity: 2
        },
        AddCategoryRequest: {
            name: "Phones"
        },
        UpdateCategoryRequest: {
            name: "Updated Category Name"
        },
        AddMembershipRequest: {
            name: "Bronze",
            discount_percentage: 10,
            min_items: 1,
            max_items: 5
        },
        UpdateMembershipRequest: {
            name: "Silver",
            discount_percentage: 20,
            min_items: 2,
            max_items: 10
        },
        UpdateOrderStatusRequest: {
            status: "Updated Status"
        },
        CreateOrderRequest: {
            userId: 1,
            orderNumber: "ABC123",
            membershipStatus: "Active",
            orderItems: [
                {
                    productId: 1,
                    quantity: 2
                },
                {
                    productId: 2,
                    quantity: 1
                }
            ]
        },
        AddProductRequest: {
            name: "Product Name",
            description: "Product Description",
            unitPrice: 10.0,
            discount: 0.0,
            date_added: "2024-03-14",
            imgurl: "http://example.com/image.jpg",
            quantity: 100,
            BrandId: 1,
            CategoryId: 1
        },
        UpdateProductRequest: {
            name: "Updated Product Name",
            description: "Updated Product Description",
            unitPrice: 12.0,
            discount: 0.1,
            date_added: "2024-03-15",
            imgurl: "http://example.com/updated-image.jpg",
            quantity: 90,
            BrandId: 2,
            CategoryId: 2
        }

    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})

swaggerAutogen(outputFile, endpointsFiles, doc);